### ISSUE TITLE
EPIC: Authed backend endpoints to fetch data from bittrex

### ISSUE THREAD

**Issue by matthewcm** [matthewcm/crypto#40]
This epic focuses on developing REST GETTERS endpoints for the Bittrex API, specifically for the market summaries and specific currency endpoints. The endpoints should be authenticated using Auth0.

### 1. Setup Auth0 authentication

- [x] #52
-  [x] #53
-  [x] #54
- [x] Code snippet, authentication done by applying middleware to endpoint
```js
router.get('/api/markets/summaries', authMiddleware, getMarketSummaries);
```

### 2. Develop the market summaries endpoint

- [x]   Design the API route for the market summaries endpoint (e.g., `/api/markets/summaries`)
-  [x]  Implement a controller function to fetch data from the Bittrex API (`https://api.bittrex.com/v3/markets/summaries`)
-  [x]   Add the controller function to the Express route
-  [x]   Test the endpoint with Auth0 authentication

### 3. Develop the specific currency endpoint

- [x]   Design the API route for the specific currency endpoint (e.g., `/api/markets/:currency/summary`)
- [x]   Implement a controller function to fetch data from the Bittrex API (`https://api.bittrex.com/v3/markets/{currency}/summary`)
- [x]   Add the controller function to the Express route
- [x]   Test the endpoint with Auth0 authentication

## Acceptance Criteria

-   Auth0 authentication is set up and integrated with the Express server
-   The market summaries endpoint is developed, authenticated, and tested
-   The specific currency endpoint is developed, authenticated, and tested
-   Both endpoints return data fetched from the Bittrex API
-   Code snippets are provided to help explain the epic
